### ISSUE TITLE
infer.py报错

### ISSUE THREAD

**Issue by zhuxiuh** [Cralence/SILT#2]
您好，我想问下在infer.py中，
checkpoint = torch.load(args_from_parser.ckpt)
args_model = checkpoint['configs']
checkpoint是加载的权重，里面keys就没有'configs'啊？
麻烦解答一下，谢谢！

**Comment by hanyangclarence** [comment]
你看一下你下载的是不是这个文件呢？
![image](https://github.com/hanyangclarence/SILT/assets/102408996/a4f67579-cc69-4312-bcc7-5a290db2361b)

感觉我确实写的不太清楚。前面那几个weight的链接是下载backbone的

**Comment by zhuxiuh** [comment]
哦哦好的，确实是我下载错误了，感谢！
